name: slider_listtile
description: A ListTile with a Slider.
version: 1.0.0
homepage: https://github.com/deakjahn/slider_listtile

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

funding:
  - https://buymeacoffee.com/deakjahn

topics:
  - flutter
  - slider
  - listtile-widget